### ISSUE TITLE
A query on the value of q_eval4next

### ISSUE THREAD

**Issue by fatemeiranmanesh** [SunwardTree/TRGIR#1]
I'm wondering if the inputs for deriving the value of  q_value4next  is correct (line No. 136)
I wrote it as follows:
 `     q_next, q_eval4next = self.sess.run([self.q_next, self.q_eval],
                                            feed_dict={self.s: batch_memory[:, -(self.itme_size + self.state_size):-self.itme_size],
                                                       self.item: batch_memory[:, -self.itme_size:],
                                                       self.s_: batch_memory[:, -(self.itme_size + self.state_size):-self.itme_size],
                                                       self.item_: batch_memory[:, `-self.itme_size:]})`

As we would like to know the value of q for the next state by the main network.

**Comment by SunwardTree** [comment]
self.s is not self.s_ , they are stored in different place.
Please refer to the definition at file TRGIR-DQN.py line No. 109.
